### PR TITLE
Add Advent Calendars For 2024

### PR DESCRIPTION
**Pull request by mikkoi**
Add the following calendars for 2024:

- https://blog.jetbrains.com/kotlin/2024/11/advent-of-code-2024-in-kotlin/
- https://sergeytihon.com/fsadvent/
- https://adventofsql.com/
- https://www.adventofts.com/
- https://www.htmhell.dev/adventcalendar/
- https://adventofcss.com/
- https://www.adventofjs.com/
- https://adventjs.dev/
- https://www.csadvent.christmas/
- https://www.javaadvent.com/
- https://perladvent.org/
- https://raku-advent.blog/

- https://adventofcode.com/
- https://www.mathekalender.de/wp/calendar/
- https://festivetechcalendar.com/
- https://24pullrequests.com/
- https://adventofopensource.com/

### CODE REVIEW

**Comment by vampirechicken** [comment]
Hey,thanks for your contribution.

**Comment by oalders** [comment]
Would it be possible to add https://qiita.com/advent-calendar/2024/perl to this list?

**Comment by vampirechicken** [comment]
Probably

**Comment by vampirechicken** [comment]
added

**Pull request closed without merging**
